INSERT INTO livro(id, qtdpaginas, titulo) VALUES (1, 120, 'Medo De Palhaco - Generale');
INSERT INTO livro(id, qtdpaginas, titulo) VALUES (2, 70, 'Narnia');
INSERT INTO livro(id, qtdpaginas, titulo) VALUES (3, 230, 'Ponto De Impacto');
INSERT INTO livro(id, qtdpaginas, titulo) VALUES (4, 360, 'Marley e Eu');
INSERT INTO livro(id, qtdpaginas, titulo) VALUES (5, 282, 'O Poderoso Chefão');
INSERT INTO livro(id, qtdpaginas, titulo) VALUES (6, 345, 'O Lado Bom da Vida');
INSERT INTO livro(id, qtdpaginas, titulo) VALUES (7, 560, 'Java Efetivo');
INSERT INTO livro(id, qtdpaginas, titulo) VALUES (8, 321, 'JPA Efetivo');
INSERT INTO livro(id, qtdpaginas, titulo) VALUES (9, 456, 'JSF Efetivo');
INSERT INTO livro(id, qtdpaginas, titulo) VALUES (10, 258, 'Harry Poter');
INSERT INTO livro(id, qtdpaginas, titulo) VALUES (11, 369, 'Animais Fantasticos');
INSERT INTO livro(id, qtdpaginas, titulo) VALUES (12, 147, 'Game Of Thrones');
INSERT INTO livro(id, qtdpaginas, titulo) VALUES (13, 159, 'Oz');
INSERT INTO livro(id, qtdpaginas, titulo) VALUES (14, 357, 'Jogos Vorazes');
INSERT INTO livro(id, qtdpaginas, titulo) VALUES (15, 256, 'Maze Runner');
INSERT INTO livro(id, qtdpaginas, titulo) VALUES (16, 365, 'Divergente');
INSERT INTO livro(id, qtdpaginas, titulo) VALUES (17, 750, 'Bíblia');
INSERT INTO livro(id, qtdpaginas, titulo) VALUES (18, 324, 'O Diário de um Banana');
INSERT INTO livro(id, qtdpaginas, titulo) VALUES (19, 432, 'Turma da Monica');
INSERT INTO livro(id, qtdpaginas, titulo) VALUES (20, 183, 'Homem Aranha');

